# Generated by Django 6.1.1 on 2026-09-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Direct phone or WhatsApp number for buyers to contact you', max_length=25),
        ),
    ]
